stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build alkostudents:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - alkostudents-back-tag
  script:
    - ./gradlew assemble

deploy alkostudents:
  stage: deploy
  tags:
    - alkostudents-back-tag
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r build/libs/. ~/api-deployment
