stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build alkostudents:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - alkostudents-back-tag
  script:
    - ./gradlew assemble

test alkostudents:
  stage: test
  tags:
    - alkostudents-back-tag
  script:
    - ./gradlew check
