server:
  port: 8000
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    #datasource:
    #url: jdbc:postgresql://localhost:5632/postgres
    #username: root
    #password: root
    datasource:
      url: jdbc:h2:~/Alkostudents_db;AUTO_SERVER=TRUE
      driverClassName: org.h2.Driver
      username: test
      password: test
  h2:
    console:
      enabled: true
