server:
  port: 9000
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/alkostudentsdb
    username: alkouser
    password: alkouserpw
logging:
  path: ./logs